controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /{_locale}
    controller: App\Controller\HomeController::index
    requirements:
        _locale: fr|en|es